// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace ArtWork;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"ArtWork.Views.HomeLandingPage", typeof(ArtWork.Views.HomeLandingPage)},
        {"ArtWork.Views.GalleryPage", typeof(ArtWork.Views.GalleryPage)},
        {"ArtWork.Views.ArtWorkPage", typeof(ArtWork.Views.ArtWorkPage)},
        {"ArtWork.Views.DownloadPage", typeof(ArtWork.Views.DownloadPage)},
        {"ArtWork.Views.DataBasePage", typeof(ArtWork.Views.DataBasePage)},
    };
}
