//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWork.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtWork.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این برنامه بر پایه برنامه ی یونیورسال  CityArt طراحی شده است. با تشکر ویژه از Brian Kernan.
        /// </summary>
        public static string AboutNote {
            get {
                return ResourceManager.GetString("AboutNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنرمند.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آثار هنری.
        /// </summary>
        public static string ArtWork {
            get {
                return ResourceManager.GetString("ArtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش خودکار.
        /// </summary>
        public static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقف فعالیت.
        /// </summary>
        public static string CancelTask {
            get {
                return ResourceManager.GetString("CancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر پوشه.
        /// </summary>
        public static string ChangeDirectory {
            get {
                return ResourceManager.GetString("ChangeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد از تغییر زبان باید برنامه را مجددا راه اندازی کنید ادامه می دهید؟.
        /// </summary>
        public static string ChangeLangAsk {
            get {
                return ResourceManager.GetString("ChangeLangAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه جستجو را انتخاب کنید.
        /// </summary>
        public static string ComboSearchItem {
            get {
                return ResourceManager.GetString("ComboSearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما از آخرین نسخه {0} استفاده می کنید.
        /// </summary>
        public static string CurrentIsLastVersion {
            get {
                return ResourceManager.GetString("CurrentIsLastVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلودر.
        /// </summary>
        public static string Downloader {
            get {
                return ResourceManager.GetString("Downloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال دانلود....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده با کیفیت اصلی.
        /// </summary>
        public static string FullScreenSee {
            get {
                return ResourceManager.GetString("FullScreenSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به محل فایل.
        /// </summary>
        public static string GoToLoc {
            get {
                return ResourceManager.GetString("GoToLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم های دانلود شده.
        /// </summary>
        public static string ItemsDownloaded {
            get {
                return ResourceManager.GetString("ItemsDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر زبان.
        /// </summary>
        public static string Langu {
            get {
                return ResourceManager.GetString("Langu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string MenuAboutWindow {
            get {
                return ResourceManager.GetString("MenuAboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string MenuConfig {
            get {
                return ResourceManager.GetString("MenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود/بروزرسانی آثار.
        /// </summary>
        public static string MenuDownload {
            get {
                return ResourceManager.GetString("MenuDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string MenuEmail {
            get {
                return ResourceManager.GetString("MenuEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی.
        /// </summary>
        public static string MenuUpdate {
            get {
                return ResourceManager.GetString("MenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه جدید {0} پیدا شد, همین حالا به آخرین نسخه بروزرسانی کنید.
        /// </summary>
        public static string NewVersionFind {
            get {
                return ResourceManager.GetString("NewVersionFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجه: برای نمایش اطلاعات هر اثر روی آن یکبار کلیک کنید.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر برهنگی.
        /// </summary>
        public static string NudeFilter {
            get {
                return ResourceManager.GetString("NudeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد آیتم ها.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشه آثار.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه نویس : سید مهدی حسینی.
        /// </summary>
        public static string Programmer {
            get {
                return ResourceManager.GetString("Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در هنرمندان....
        /// </summary>
        public static string SearchInArtists {
            get {
                return ResourceManager.GetString("SearchInArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در شهر ها....
        /// </summary>
        public static string SearchInCity {
            get {
                return ResourceManager.GetString("SearchInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در کشورها....
        /// </summary>
        public static string SearchInCountry {
            get {
                return ResourceManager.GetString("SearchInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در گالری موزه ها....
        /// </summary>
        public static string SearchInGallery {
            get {
                return ResourceManager.GetString("SearchInGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در تصاویر....
        /// </summary>
        public static string SearchInImages {
            get {
                return ResourceManager.GetString("SearchInImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم به عنوان پس زمینه.
        /// </summary>
        public static string SetasDesktop {
            get {
                return ResourceManager.GetString("SetasDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام وظایف لغو شد.
        /// </summary>
        public static string TaskCanceled {
            get {
                return ResourceManager.GetString("TaskCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کل آیتم ها.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
    }
}
