//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtWork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aarhus
        ///Aberdeen
        ///Aberdeenshire
        ///Abu Dhabi
        ///Adana
        ///Adelaide
        ///Agra
        ///Ahmedabad
        ///Aix-en-Provence
        ///Ajaccio
        ///Alatskivi
        ///Albi
        ///Alexandria
        ///Alfriston
        ///Alice Springs
        ///Alta
        ///Altenburg
        ///Amarante
        ///Amersfoort
        ///Amherst
        ///Amiens
        ///Amman
        ///Amritsar
        ///Amsterdam
        ///Ancona
        ///Andover
        ///Angers
        ///Ann Arbor
        ///Annandale-on-Hudson
        ///Antalya
        ///Antwerp
        ///Aparecida
        ///Ardingly
        ///Ardأ¨che
        ///Arezzo
        ///Aschaffenburg
        ///Asciano
        ///Athens
        ///Atlanta
        ///Auckland
        ///Austin
        ///Avignon
        ///Axum
        ///Ballarat
        ///Baltimore
        ///Bam
        ///Bandel
        ///Bangalore
        ///Bangkok
        ///Barcelona
        ///Barnard Castle
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania
        ///Argentina
        ///Armenia
        ///Australia
        ///Austria
        ///Bangladesh
        ///Belgium
        ///Brazil
        ///Bulgaria
        ///Canada
        ///Chile
        ///China
        ///Colombia
        ///Croatia
        ///Cuba
        ///Cyprus
        ///Czech Republic
        ///Denmark
        ///Egypt
        ///Empty
        ///England
        ///Estonia
        ///Ethiopia
        ///Finland
        ///France
        ///Georgia
        ///Germany
        ///Ghana
        ///Greece
        ///Greenland
        ///Hungary
        ///India
        ///Indonesia
        ///Iran
        ///Iraq
        ///Ireland
        ///Israel
        ///Italy
        ///Japan
        ///Jordan
        ///Kuwait
        ///Latvia
        ///Libya
        ///Liechtenstein
        ///Macedonia
        ///Malaysia
        ///Malta
        ///Mexico
        ///Monaco
        ///Netherlands
        ///New Zealand
        ///North Korea
        ///Northern Ireland
        ///Norway
        ///Oman
        ///Pakistan
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 Spruce Street
        ///Abbey of Saint-Michel-de-Cuxa
        ///Abbey of St. Gall
        ///Aberdeen Art Gallery
        ///Academy of Athens
        ///Academy of Fine Arts
        ///Accademia Carrara
        ///Accademia di San Luca
        ///Ackland Art Museum
        ///Acropolis Museum
        ///Adachi Museum of Art
        ///Addison Gallery of American Art
        ///African Renaissance Monument
        ///Agnes Etherington Art Centre
        ///Agora
        ///Ahsan Manzil
        ///Aivazovsky National Art Gallery
        ///Al-Aqsa Mosque
        ///Al-Khazneh
        ///Alatskivi Castle
        ///Albert Bridge
        ///Albert Memorial
        ///Albertina
        ///Albright-Knox Art Gallery
        ///Alexander Column        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7
        ///8
        ///14
        ///15
        ///16
        ///20
        ///30
        ///31
        ///32
        ///43
        ///50
        ///75
        ///105
        ///114
        ///120
        ///121
        ///122
        ///141
        ///171
        ///172
        ///198
        ///201
        ///202
        ///203
        ///242
        ///243
        ///248
        ///324
        ///338
        ///386
        ///387
        ///388
        ///397
        ///398
        ///404
        ///407
        ///418
        ///426
        ///428
        ///441
        ///453
        ///458
        ///464
        ///485
        ///495
        ///505
        ///518
        ///525
        ///535
        ///543
        ///545
        ///546
        ///547
        ///551
        ///567
        ///583
        ///699
        ///703
        ///706
        ///729
        ///730
        ///731
        ///732
        ///733
        ///734
        ///738
        ///762
        ///763
        ///764
        ///765
        ///766
        ///767
        ///768
        ///769
        ///770
        ///782
        ///784
        ///785
        ///789
        ///790
        ///793
        ///796
        ///801
        ///805
        ///808
        ///811
        ///818
        ///821
        ///824
        ///826
        ///839
        ///842
        ///843
        ///851
        ///858
        ///880
        ///901
        ///913
        ///920
        ///923
        ///925
        ///937
        ///941
        ///942
        ///953
        ///9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nudes {
            get {
                return ResourceManager.GetString("nudes", resourceCulture);
            }
        }
    }
}
