//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtWork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtWork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7
        ///8
        ///14
        ///15
        ///16
        ///20
        ///30
        ///31
        ///32
        ///43
        ///50
        ///75
        ///105
        ///114
        ///120
        ///121
        ///122
        ///141
        ///171
        ///172
        ///198
        ///201
        ///202
        ///203
        ///242
        ///243
        ///248
        ///324
        ///338
        ///386
        ///387
        ///388
        ///397
        ///398
        ///404
        ///407
        ///418
        ///426
        ///428
        ///441
        ///453
        ///458
        ///464
        ///485
        ///495
        ///505
        ///518
        ///525
        ///535
        ///543
        ///545
        ///546
        ///547
        ///551
        ///567
        ///583
        ///699
        ///703
        ///706
        ///729
        ///730
        ///731
        ///732
        ///733
        ///734
        ///738
        ///762
        ///763
        ///764
        ///765
        ///766
        ///767
        ///768
        ///769
        ///770
        ///782
        ///784
        ///785
        ///789
        ///790
        ///793
        ///796
        ///801
        ///805
        ///808
        ///811
        ///818
        ///821
        ///824
        ///826
        ///839
        ///842
        ///843
        ///851
        ///858
        ///880
        ///901
        ///913
        ///920
        ///923
        ///925
        ///937
        ///941
        ///942
        ///953
        ///9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nudes {
            get {
                return ResourceManager.GetString("nudes", resourceCulture);
            }
        }
    }
}
